version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    environment:
      - 'SPRING_PROFILES_ACTIVE=test'
    ports:
      - '8080:8080'
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '3000:3000'
